/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.overseaslabs.examples.ureg;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        assertTrue(true);
    }
}
